{
 "title": "Arks Runtime Monitoring",
 "description": "Monitoring Runtime",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "model_name",
    "label": "model_name",
    "query": {
     "query": "label_values(time_to_first_token_seconds_count,model_name)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(time_to_first_token_seconds_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Request Count(Stop)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(runtime) (increase(request_success_total{finished_reason=\"stop\", model_name=\"$model_name\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum by(runtime) (increase(num_requests_total{model_name=\"$model_name\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (increase(request_prompt_tokens_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (increase(request_generation_tokens_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prompt & Decode Length",
   "type": "timeseries",
   "description": "Prompt & Decode length",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(request_prompt_tokens_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Prompt-P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(request_prompt_tokens_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Prompt-P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(request_prompt_tokens_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Prompt-P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(request_generation_tokens_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Decode-P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(request_generation_tokens_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Decode-P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(request_generation_tokens_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Decode-P50"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(e2e_request_latency_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(e2e_request_latency_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(e2e_request_latency_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(e2e_request_latency_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(rate(e2e_request_latency_seconds_sum{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])\n/\nrate(e2e_request_latency_seconds_count{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(time_to_first_token_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(time_to_first_token_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(time_to_first_token_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_to_first_token_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(rate(time_to_first_token_seconds_sum{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])\n/\nrate(time_to_first_token_seconds_count{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Inter token latency in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(time_per_output_token_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(time_per_output_token_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(time_per_output_token_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_per_output_token_seconds_bucket{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(time_per_output_token_seconds_sum{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])\n/\nrate(time_per_output_token_seconds_count{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Prompt Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(job)(rate(prompt_tokens_total{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "tokens/s({{job}})"
    },
    {
     "expr": "sum (rate(prompt_tokens_total{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "tokens/s(SUM)"
    }
   ]
  },
  {
   "title": "Decode Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum by(job) (rate(generation_tokens_total{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "tokens/s({{job}})"
    },
    {
     "expr": "sum (rate(generation_tokens_total{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "tokens/s(ALL)"
    }
   ]
  },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (num_requests_running{model_name=\"$model_name\", namespace=\"$namespace\"})",
     "legendFormat": "Num Running"
    },
    {
     "expr": "sum(num_requests_swapped{model_name=\"$model_name\", namespace=\"$namespace\"})",
     "legendFormat": "Num Swapped"
    },
    {
     "expr": "sum(num_requests_waiting{model_name=\"$model_name\", namespace=\"$namespace\"})",
     "legendFormat": "Num Waiting"
    }
   ]
  },
  {
   "title": "Prefix Cache Hit Rate",
   "type": "timeseries",
   "description": "Percentage of prefix cache hit rate",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(gpu_prefix_cache_hits_total{model_name=\"$model_name\", namespace=\"$namespace\"}[$__interval]) / rate(gpu_prefix_cache_queries_total{model_name=\"$model_name\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "GPU Prefix Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(gpu_cache_usage_perc{model_name=\"$model_name\", namespace=\"$namespace\"})",
     "legendFormat": "GPU Cache Usage"
    },
    {
     "expr": "avg(cpu_cache_usage_perc{model_name=\"$model_name\", namespace=\"$namespace\"})",
     "legendFormat": "CPU Cache Usage"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(request_success_total{model_name=\"$model_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num Running Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(job) (num_requests_running{model_name=\"$model_name\", namespace=\"$namespace\"}) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Num Waiting Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum by(job) (num_requests_waiting{model_name=\"$model_name\", namespace=\"$namespace\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}